version: '2'

services:
  web:
    command: npm run dev
    build: .
    volumes:
      - ./:/app
    ports:
      - "80:8080"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/freeiot-api
      - MQTT_SERVER=mqtt
      - MQTT_PORT=1883

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  mongodata:
    image: tianon/true
    volumes:
      - /data/db
